### ISSUE TITLE
Deploy AV Control API and all drivers into our kubernetes cluster

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/av-control-api#43]
A few decisions to make:
1. One pod for all or a pod for each driver?
1. Terraform with each driver, or one terraform file at the root that deploys everything?
1. Should drivers be publicly accessible? 

I would say it makes the most sense to do the following:
1. One pod per driver so that it can scale individually
1. I don't have a strong preference, but I would prefer one terraform file that manages everything.
1. Only allow drivers to be reached from within the cluster

Let me know if any of you have other ideas/concerns @byuoitav/avengineers.

**Comment by bwinterton** [comment]
I agree with all three decisions. One pod each, one terraform file, and only private access.
