### ISSUE TITLE
Proposal: Simplify and add deployment environments to device-type config

### ISSUE THREAD

**Issue by bwinterton** [byuoitav/av-control-api#63]
We have hit an issue in our new deployment of the AV API and driver microservices into k8s in AWS. Currently, the AV API reads the `device_types` configuration from couch and finds drivers given that information. This has worked previously as we ensured that the hostnames for drivers matched between the pis and AWS. However, in our new k8s infrastructure we made a different decision to separate the drivers from the AV-API, allowing individual pieces of the infrastructure to scale separately and be managed separately as needed. This decision has pushed microservices to have different hostnames and ports than they do on the pis. 

This has driven a new requirement for the AV API:
* The AV API should be able to find the required driver microservices in distinct deployment environments. 

## Changes to `device_types`
Note: This proposal also includes some of the changes suggested in #27 for convenience as we will already be touching this code. 
* `commands` becomes a map of CommandID to an object that includes the following fields:
  * `addresses`: a map of deployment environment name to the full URL of the request for the av-api to send
    * _Must_ be written using [template syntax](https://golang.org/pkg/text/template/), with the variable names matching what is "passed" to the [driver interfaces](https://github.com/byuoitav/av-control-api/tree/master/drivers)
      * Note: at some future point these will be processed with the Go template library, but until a more extensive rewrite is complete we will use a "half-way" approach where "mustache" tags are used, but the values will not be properties on a struct (ie `{{address}}` not `{{.Address}}`)
    * _Should_ include a `fallback` key, the fallback key will be used:
      * When a deployment environment is not passed to the AV API at startup
      * When the desired deployment environment is not configured with a matching address
      * Longer explanation given in [this comment](https://github.com/byuoitav/av-control-api/issues/63#issuecomment-597896621)
  * `order`: if multiple actions are generated at the same time, this defines the order they should be executed in. If `order` is missing, the command is placed after all `order`'d commands
  * remove `description`
  * remove `microservice` object
  * remove `endpoint` object

These changes result in a document that looks like this: 
```json
{
  "_id": "Atlona4x1",
  "description": "Atlona 4x1 Video Switcher",
  "display_name": "Atlona Video Switcher - 4x1",
  "source": true,
  "destination": true,
  "roles": [...],
  "ports": [...],
  "commands": {
    "ChangeInput": {
        "addresses": {
          "fallback": "http://localhost:8026/{{address}}/output/{{output}}/input/{{input}}",
          "aws": "http://atlona-driver-prd/{{address}}/output/{{output}}/input/{{input}}"
        },
        "order": 10
    },
    "InputStatus": {
        "addresses": {
          "fallback": "http://localhost:8026/{{address}}/output/{{port}}",
          "aws": "http://atlona-driver-prd/{{address}}/output/{{port}}"
        },
        "order": 10
    }
  },
  "tags": [...]
}
```

**Comment by bwinterton** [comment]
Edited to change `default` key to `fallback`

**Comment by dannyrandall** [comment]
This looks great. I think you can remove this bit, it was probably from a previous iteration.
> Create a new drivers array at the root of the document

**Comment by bwinterton** [comment]
Edited to remove old mentions of past proposal

**Comment by dannyrandall** [comment]
We should probably include how the API selects a deployment environment: A flag is passed to the program specifying which environment to look for. The default value for that flag would be `fallback` (or could be unset, the behavior would be the same) and would use the fallback address for every command.

**Comment by bwinterton** [comment]
Clarification on `fallback`:

The theory is, we will add a `deployment_environment` flag to the AV API, which will be specified at startup. If the specified environment cannot be found (hasn't been defined in the config) when looking up the address for the command being run, the AV API will instead use the fallback address. This is useful in a few scenarios:
* When we accidentally define an environment that doesn't exist the API still functions in a 'default' scenario
* If we are using only a few different drivers in a given environment, the environment does not have to be defined on drivers which can use the defaults
* If a device type is mistakenly not updated, functionality _may_ continue to exist using the fallback

Fallback will also be the 'environment' utilized when a flag is not passed to the AV API.

**Comment by bwinterton** [comment]
Several edits to try to include the succinct definition of `fallback`

**Comment by thailandmatt** [comment]
I concur.

**Comment by bwinterton** [comment]
I haven't heard any dissent, so I'm going to consider this proposal semi-approved for the moment and start the work. If there is any disagreement speak now or forever hold your peace.

**Comment by bwinterton** [comment]
Approved
